//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFTP.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFTP.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity is to delete the file from the remote server.
        /// </summary>
        public static string SFTPDelete_Description {
            get {
                return ResourceManager.GetString("SFTPDelete_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFTP Delete.
        /// </summary>
        public static string SFTPDelete_DisplayName {
            get {
                return ResourceManager.GetString("SFTPDelete_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name.
        /// </summary>
        public static string SFTPDelete_Host_Description {
            get {
                return ResourceManager.GetString("SFTPDelete_Host_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string SFTPDelete_Host_DisplayName {
            get {
                return ResourceManager.GetString("SFTPDelete_Host_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Details.
        /// </summary>
        public static string SFTPDelete_Password_Description {
            get {
                return ResourceManager.GetString("SFTPDelete_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SFTPDelete_Password_DisplayName {
            get {
                return ResourceManager.GetString("SFTPDelete_Password_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Number.
        /// </summary>
        public static string SFTPDelete_Port_Description {
            get {
                return ResourceManager.GetString("SFTPDelete_Port_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string SFTPDelete_Port_DisplayName {
            get {
                return ResourceManager.GetString("SFTPDelete_Port_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SFTPDelete_RemoteFileFullPath_Description {
            get {
                return ResourceManager.GetString("SFTPDelete_RemoteFileFullPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote File Full Path.
        /// </summary>
        public static string SFTPDelete_RemoteFileFullPath_DisplayName {
            get {
                return ResourceManager.GetString("SFTPDelete_RemoteFileFullPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Details.
        /// </summary>
        public static string SFTPDelete_UserName_Description {
            get {
                return ResourceManager.GetString("SFTPDelete_UserName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string SFTPDelete_UserName_DisplayName {
            get {
                return ResourceManager.GetString("SFTPDelete_UserName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity is to download the files from the sftp server.
        /// </summary>
        public static string SFTPFileDownload_Description {
            get {
                return ResourceManager.GetString("SFTPFileDownload_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFTP File Download.
        /// </summary>
        public static string SFTPFileDownload_DisplayName {
            get {
                return ResourceManager.GetString("SFTPFileDownload_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name.
        /// </summary>
        public static string SFTPFileDownload_Host_Description {
            get {
                return ResourceManager.GetString("SFTPFileDownload_Host_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string SFTPFileDownload_Host_DisplayName {
            get {
                return ResourceManager.GetString("SFTPFileDownload_Host_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Path to save the file.
        /// </summary>
        public static string SFTPFileDownload_LocalPath_Description {
            get {
                return ResourceManager.GetString("SFTPFileDownload_LocalPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Path.
        /// </summary>
        public static string SFTPFileDownload_LocalPath_DisplayName {
            get {
                return ResourceManager.GetString("SFTPFileDownload_LocalPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Details.
        /// </summary>
        public static string SFTPFileDownload_Password_Description {
            get {
                return ResourceManager.GetString("SFTPFileDownload_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SFTPFileDownload_Password_DisplayName {
            get {
                return ResourceManager.GetString("SFTPFileDownload_Password_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Number.
        /// </summary>
        public static string SFTPFileDownload_Port_Description {
            get {
                return ResourceManager.GetString("SFTPFileDownload_Port_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string SFTPFileDownload_Port_DisplayName {
            get {
                return ResourceManager.GetString("SFTPFileDownload_Port_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source path of the file in remote directory.
        /// </summary>
        public static string SFTPFileDownload_RemoteFullPath_Description {
            get {
                return ResourceManager.GetString("SFTPFileDownload_RemoteFullPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Full Path.
        /// </summary>
        public static string SFTPFileDownload_RemoteFullPath_DisplayName {
            get {
                return ResourceManager.GetString("SFTPFileDownload_RemoteFullPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Details.
        /// </summary>
        public static string SFTPFileDownload_UserName_Description {
            get {
                return ResourceManager.GetString("SFTPFileDownload_UserName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string SFTPFileDownload_UserName_DisplayName {
            get {
                return ResourceManager.GetString("SFTPFileDownload_UserName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity is to Upload the files from to sftp server.
        /// </summary>
        public static string SFTPFileUpLoad_Description {
            get {
                return ResourceManager.GetString("SFTPFileUpLoad_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFTP File UpLoad.
        /// </summary>
        public static string SFTPFileUpLoad_DisplayName {
            get {
                return ResourceManager.GetString("SFTPFileUpLoad_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name.
        /// </summary>
        public static string SFTPFileUpLoad_Host_Description {
            get {
                return ResourceManager.GetString("SFTPFileUpLoad_Host_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string SFTPFileUpLoad_Host_DisplayName {
            get {
                return ResourceManager.GetString("SFTPFileUpLoad_Host_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local file full path.
        /// </summary>
        public static string SFTPFileUpLoad_LocalPath_Description {
            get {
                return ResourceManager.GetString("SFTPFileUpLoad_LocalPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Path.
        /// </summary>
        public static string SFTPFileUpLoad_LocalPath_DisplayName {
            get {
                return ResourceManager.GetString("SFTPFileUpLoad_LocalPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SFTPFileUpLoad_Password_Description {
            get {
                return ResourceManager.GetString("SFTPFileUpLoad_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SFTPFileUpLoad_Password_DisplayName {
            get {
                return ResourceManager.GetString("SFTPFileUpLoad_Password_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Number.
        /// </summary>
        public static string SFTPFileUpLoad_Port_Description {
            get {
                return ResourceManager.GetString("SFTPFileUpLoad_Port_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string SFTPFileUpLoad_Port_DisplayName {
            get {
                return ResourceManager.GetString("SFTPFileUpLoad_Port_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote directory path.
        /// </summary>
        public static string SFTPFileUpLoad_RemoteFilePath_Description {
            get {
                return ResourceManager.GetString("SFTPFileUpLoad_RemoteFilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote file Path.
        /// </summary>
        public static string SFTPFileUpLoad_RemoteFilePath_DisplayName {
            get {
                return ResourceManager.GetString("SFTPFileUpLoad_RemoteFilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string SFTPFileUpLoad_UserName_Description {
            get {
                return ResourceManager.GetString("SFTPFileUpLoad_UserName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string SFTPFileUpLoad_UserName_DisplayName {
            get {
                return ResourceManager.GetString("SFTPFileUpLoad_UserName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
